### ISSUE TITLE
[Subworkflow] Contamination search and removal

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/genomeassembler#41]
### Description of feature

Decontaminate reads / assemblies with FCS
- https://github.com/nf-core/modules/issues/1951
- https://github.com/nf-core/modules/issues/1952

**Comment by scorreard** [comment]
Currently available here : https://github.com/scorreard/modules/tree/fasta_clean_fcs

**Comment by scorreard** [comment]
Do we want to push it to subworkflow/nf-core or should it ultimately be in subworkflow/local?
I'll create the appropriate PR once this is settled.
